server:
  port: 9093

spring:
  application:
    name: example-job

logging:
  config: classpath:logback.xml

xxl:
  job:
    executor:
      admin-addresses: http://127.0.0.1:9000/xxl-job-admin
      app-name: example-xxl-job-executor
      log-retention-days: -1
      access-token:
      address:
      ip:
      port: 9999
      log-path:

